'use strict';
let ready=false,meta={},configs=[],destinations=[];
let nodeLat,nodeLon,nodeRoute,nodeSeq,nodeEndpoint,nodeNames;
let offsets,edgeTo,edgeDist,edgeCount,edgeConnector;
const td=new TextDecoder();
const rad=v=>v*Math.PI/180;
function hav(aLat,aLon,bLat,bLon){const p1=rad(aLat),p2=rad(bLat),dp=rad(bLat-aLat),dl=rad(bLon-aLon),h=Math.sin(dp/2)**2+Math.cos(p1)*Math.cos(p2)*Math.sin(dl/2)**2;return 3440.065*2*Math.atan2(Math.sqrt(h),Math.sqrt(Math.max(0,1-h)));}
class Reader{constructor(buffer){this.v=new DataView(buffer);this.u=new Uint8Array(buffer);this.o=0;}u32(){const x=this.v.getUint32(this.o,true);this.o+=4;return x;}f32(){const x=this.v.getFloat32(this.o,true);this.o+=4;return x;}f64(){const x=this.v.getFloat64(this.o,true);this.o+=8;return x;}byte(){return this.u[this.o++];}str(){const n=this.u32();if(n>64*1024*1024)throw new Error('Invalid planner string length');const s=td.decode(this.u.subarray(this.o,this.o+n));this.o+=n;return s;}}
async function gunzip(url){const r=await fetch(url,{cache:'force-cache'});if(!r.ok)throw new Error(`Historical planner database not found (${r.status})`);if(!('DecompressionStream'in self))throw new Error('This browser does not support gzip decompression.');return new Response(r.body.pipeThrough(new DecompressionStream('gzip'))).arrayBuffer();}
async function init(url){postMessage({type:'progress',phase:'Loading historical route catalogue',progress:.05});const buffer=await gunzip(url);postMessage({type:'progress',phase:'Parsing historical destinations and routes',progress:.18});const r=new Reader(buffer);const magic=td.decode(r.u.subarray(0,8));r.o=8;if(magic!=='LRPDATA1')throw new Error('Invalid historical planner database');const jn=r.u32();meta=JSON.parse(td.decode(r.u.subarray(r.o,r.o+jn)));r.o+=jn;const ncfg=r.u32();configs=[];for(let i=0;i<ncfg;i++)configs.push({name:r.str(),maxRPM:r.f32(),speedKn:r.f32(),consumptionMtDay:r.f32(),loadPct:r.f32()});const nd=r.u32();destinations=[];for(let i=0;i<nd;i++){const name=r.str(),aliases=JSON.parse(r.str()||'[]'),lat=r.f64(),lon=r.f64(),category=r.str(),count=r.u32();destinations.push({name,aliases,lat,lon,category,count});}
const nn=r.u32();nodeLat=new Float64Array(nn);nodeLon=new Float64Array(nn);nodeRoute=new Uint32Array(nn);nodeSeq=new Uint32Array(nn);nodeEndpoint=new Uint8Array(nn);nodeNames=new Array(nn);for(let i=0;i<nn;i++){nodeLat[i]=r.f64();nodeLon[i]=r.f64();nodeNames[i]=r.str();nodeRoute[i]=r.u32();nodeSeq[i]=r.u32();nodeEndpoint[i]=r.byte();if(i%5000===0)postMessage({type:'progress',phase:'Loading historical route nodes',progress:.2+.25*i/nn});}
const ne=r.u32(),from=new Uint32Array(ne),to=new Uint32Array(ne),dist=new Float32Array(ne),counts=new Uint32Array(ne),conn=new Uint8Array(ne),degree=new Uint32Array(nn);for(let i=0;i<ne;i++){from[i]=r.u32();to[i]=r.u32();dist[i]=r.f32();counts[i]=r.u32();conn[i]=r.byte();r.f32();r.f32();r.f32();r.f32();if(from[i]<nn)degree[from[i]]++;if(i%50000===0)postMessage({type:'progress',phase:'Building historical corridor graph',progress:.46+.35*i/ne});}
offsets=new Uint32Array(nn+1);for(let i=0;i<nn;i++)offsets[i+1]=offsets[i]+degree[i];const cursor=offsets.slice();edgeTo=new Uint32Array(ne);edgeDist=new Float32Array(ne);edgeCount=new Uint32Array(ne);edgeConnector=new Uint8Array(ne);for(let i=0;i<ne;i++){const f=from[i];if(f>=nn)continue;const p=cursor[f]++;edgeTo[p]=to[i];edgeDist[p]=dist[i];edgeCount[p]=counts[i];edgeConnector[p]=conn[i];}
ready=true;postMessage({type:'ready',meta,configs,destinations});}
function endpointCandidates(lat,lon){const rows=new Array(nodeLat.length);for(let i=0;i<nodeLat.length;i++)rows[i]={node:i,dist:hav(lat,lon,nodeLat[i],nodeLon[i])};rows.sort((a,b)=>a.dist-b.dist);if(!rows.length)return[];const nearest=rows[0].dist,limit=Math.min(45,Math.max(3,nearest+4)),out=[],perRoute=new Map();for(const c of rows){if(c.dist>limit||out.length>=24)break;const rid=nodeRoute[c.node],n=perRoute.get(rid)||0;if(n>=2)continue;perRoute.set(rid,n+1);out.push(c);}return out;}
class Heap{constructor(){this.a=[];}push(x){const a=this.a;a.push(x);let i=a.length-1;while(i){const p=(i-1)>>1;if(a[p].f<=x.f)break;a[i]=a[p];i=p;}a[i]=x;}pop(){const a=this.a;if(!a.length)return null;const root=a[0],last=a.pop();if(a.length){let i=0;while(true){let l=i*2+1,r=l+1;if(l>=a.length)break;let c=r<a.length&&a[r].f<a[l].f?r:l;if(a[c].f>=last.f)break;a[i]=a[c];i=c;}a[i]=last;}return root;}get length(){return this.a.length;}}
function findPath(start,end){const starts=endpointCandidates(start.lat,start.lon),ends=endpointCandidates(end.lat,end.lon);if(!starts.length||!ends.length||starts[0].dist>45||ends[0].dist>45)throw new Error('No historical route network was found close enough to one or both positions.');const endCost=new Map(ends.map(c=>[c.node,c.dist*1.65])),n=nodeLat.length,g=new Float64Array(n),came=new Int32Array(n);g.fill(Infinity);came.fill(-1);const heap=new Heap();for(const c of starts){const gc=c.dist*1.65;if(gc<g[c.node]){g[c.node]=gc;heap.push({node:c.node,g:gc,f:gc+.72*hav(nodeLat[c.node],nodeLon[c.node],end.lat,end.lon)});}}
let best=Infinity,bestNode=-1,visits=0;while(heap.length){const it=heap.pop();if(it.g!==g[it.node])continue;if(it.f>=best)break;const tail=endCost.get(it.node);if(tail!==undefined&&it.g+tail<best){best=it.g+tail;bestNode=it.node;}for(let p=offsets[it.node];p<offsets[it.node+1];p++){const v=edgeTo[p];let cost=edgeDist[p];if(edgeConnector[p])cost=cost*3.5+.24;else if(edgeCount[p]>1)cost/=1+Math.min(.12,.025*Math.log1p(edgeCount[p]));const ng=it.g+cost;if(ng>=g[v]||ng>=best)continue;g[v]=ng;came[v]=it.node;heap.push({node:v,g:ng,f:ng+.72*hav(nodeLat[v],nodeLon[v],end.lat,end.lon)});}if(++visits%12000===0)postMessage({type:'routeProgress',phase:'Searching historical corridor network',visits});}
if(bestNode<0)throw new Error('The historical route corridors do not form a connected passage between these positions.');const path=[];for(let x=bestNode;x>=0;x=came[x]){path.push(x);if(came[x]<0)break;}path.reverse();let network=0;for(let i=1;i<path.length;i++)network+=hav(nodeLat[path[i-1]],nodeLon[path[i-1]],nodeLat[path[i]],nodeLon[path[i]]);const direct=hav(start.lat,start.lon,end.lat,end.lon);if(direct>5&&network>direct*2.6+80)throw new Error('Historical network solution is an excessive detour; no reliable route was generated.');return path;}
function bearing(a,b){const p1=rad(a.lat),p2=rad(b.lat),dl=rad(b.lon-a.lon);return (Math.atan2(Math.sin(dl)*Math.cos(p2),Math.cos(p1)*Math.sin(p2)-Math.sin(p1)*Math.cos(p2)*Math.cos(dl))*180/Math.PI+360)%360;}
function angleDiff(a,b){let d=Math.abs(a-b)%360;return d>180?360-d:d;}
function simplify(points){if(points.length<=2)return points;const total=points.reduce((s,p,i)=>i?s+hav(points[i-1].lat,points[i-1].lon,p.lat,p.lon):0,0),minLeg=total>1000?5:total>300?2.5:total>80?1.2:.4;const out=[points[0]];for(let i=1;i<points.length-1;i++){const prev=out[out.length-1],cur=points[i],next=points[i+1],d=hav(prev.lat,prev.lon,cur.lat,cur.lon),turn=angleDiff(bearing(prev,cur),bearing(cur,next));if(cur.endpoint||cur.name||d>=minLeg||turn>=6)out.push(cur);}out.push(points.at(-1));if(out.length<=220)return out;const limited=[out[0]],step=(out.length-1)/219;for(let i=1;i<219;i++)limited.push(out[Math.round(i*step)]);limited.push(out.at(-1));return limited;}
function generate(start,end,speed){const path=findPath(start,end),points=[{lat:start.lat,lon:start.lon,name:start.name,endpoint:true}];for(const id of path){const p={lat:nodeLat[id],lon:nodeLon[id],name:nodeNames[id]||'',endpoint:!!nodeEndpoint[id],routeId:nodeRoute[id]};if(hav(points.at(-1).lat,points.at(-1).lon,p.lat,p.lon)<.015){if(!points.at(-1).name)points.at(-1).name=p.name;continue;}points.push(p);}if(hav(points.at(-1).lat,points.at(-1).lon,end.lat,end.lon)>.015)points.push({lat:end.lat,lon:end.lon,name:end.name,endpoint:true});else Object.assign(points.at(-1),{name:end.name,endpoint:true});const clean=simplify(points),radius=speed<7?.3:speed<=12?.5:1;return clean.map((p,i)=>({name:p.name||(i===0?start.name:i===clean.length-1?end.name:`WP${String(i+1).padStart(3,'0')}`),lat:p.lat,lon:p.lon,radius,speed,portXtd:.1,starboardXtd:.1,wheelOver:0,geometry:'Loxodrome',remarks:p.endpoint?'Historical operational marker':''}));}
onmessage=async e=>{const m=e.data||{};try{if(m.type==='init'){await init(m.url||'./assets/planner.bin.gz');return;}if(m.type==='route'){if(!ready)throw new Error('Historical planner data is still loading.');const waypoints=generate(m.start,m.end,Number(m.speed)||10);postMessage({type:'routeResult',requestId:m.requestId,waypoints});}}catch(error){postMessage({type:m.type==='route'?'routeError':'error',requestId:m.requestId,message:error.message||String(error)});}};
